fileVersion: 1
id: "198"
mappingDefinitions:
  SRC:
    database: JOSH_DEV
    schema: SRC_COALESCE
  TARGET:
    database: JOSH_DEV
    schema: TARGET_COALESCE
name: New Environment
type: Environment
