@id("60b54348-3e63-4704-8964-ad8653ce4cae")
@nodeType("2e4db651-fdf8-4b90-ac51-636cbd0c5767")
SELECT
     "O_ORDERKEY" AS "O_ORDERKEY",
     "O_CUSTKEY" AS "O_CUSTKEY",
     "O_ORDERSTATUS" AS "O_ORDERSTATUS",
     "O_TOTALPRICE" AS "O_TOTALPRICE",
     "O_ORDERDATE" AS "O_ORDERDATE",
     "O_ORDERPRIORITY" AS "O_ORDERPRIORITY",
     "O_CLERK" AS "O_CLERK",
     "O_SHIPPRIORITY" AS "O_SHIPPRIORITY",
     "O_COMMENT" AS "O_COMMENT"
FROM {{ ref('SRC', 'ORDERS') }} "ORDERS"