@id("different-nodeid")
@nodeType("2e4db651-fdf8-4b90-ac51-636cbd0c5767")
SELECT O."O_ORDERKEY", 
CASE WHEN "O"."O_ORDERSTATUS" = 'F' AND "O"."O_TOTALPRICE" IS NOT NULL THEN 1 ELSE 0 END AS "IS_FULFILLED", CASE WHEN "O"."O_TOTALPRICE" > 100000 THEN 'High' WHEN "O"."O_TOTALPRICE" > 10000 THEN 'Medium' ELSE 'Low' END AS "PRICE_TIER", CASE WHEN "O"."O_ORDERPRIORITY" = '1-URGENT' THEN TRUE ELSE FALSE END AS "IS_URGENT" 
FROM {{ ref('SRC', 'ORDERS') }} O